### PR TITLE
return an error on wrong ssl.type value

### PR DESCRIPTION
**Pull request by negasus**

### CODE REVIEW

**Comment by umputun** [comment]
is there an actual problem this pr is supposed to address? SSL types handled by go-flags library and won't allow to pass anything except what defined in `choice` tags

`Type          string   `long:"type" env:"TYPE" description:"ssl (auto) support" choice:"none" choice:"static" choice:"auto" default:"none"`

**Comment by negasus** [comment]
I made this PR after I mistyped SSL_TYPE=true a couple of times myself and didn't get any error.
I believe returning an error in this case will not degrade the user experience. But it can help in finding an erroneous configuration

**Comment by umputun** [comment]
ah, you meant from env, because this `choice` handles command-line flags only I think. makes sense

```
go run app/main.go --dbg --ssl.type=true    
reproxy unknown
Invalid value `true' for option `--ssl.type'. Allowed values are: none, static or auto
2022/02/15 02:49:00 ERROR cli error: Invalid value `true' for option `--ssl.type'. Allowed values are: none, static or auto
```

**Comment by umputun** [comment]
could you please match the error your return to the one cli will throw?, just for consistency, i.e. 

`Invalid value "true" for  SSL_TYPE. Allowed values are: none, static or auto`

**Comment by umputun** [comment]
LGTM, will merge. 

the minor thing just FYI: you don't need to put `\"%s\"`, this is what `%q` is for. I'll change it after merge

**Pull request merged**
