### PR TITLE
#7 Disable image build and push on PR

### PR DESCRIPTION
**Pull request by prizov**
The PR addresses the issue #7

### CODE REVIEW

**Review by umputun — COMMENTED** [review]
Thx. It is likely will disable image build on other branches as well, which is fine, but I wonder if it allows building on tags (I.e. version release)

**Comment by prizov** [comment]
@umputun I've updated the PR. Now it builds and publish Docker image only if a pipeline gets triggered either from the master or by tag

**Comment by umputun** [comment]
LGTM

**Comment by umputun** [comment]
failed https://github.com/umputun/reproxy/actions/runs/736532747

**Pull request merged**
