### PR TITLE
Basic auth

### PR DESCRIPTION
**Pull request by umputun**
Add supports of basic auth for all requests. 

This is useful for protecting endpoints during the development and testing, before allowing unrestricted access to them. This functionality is disabled by default and not granular enough to allow for per-route auth. I.e. enabled basic auth will affect all requests.

### CODE REVIEW

**Comment by saaremaa** [comment]
Are you planning a more flexible setting for each end point?

**Comment by umputun** [comment]
> Are you planning a more flexible setting for each end point?

I'm not sure if it makes much sense. For any flexible support of basic auth, having a common static file of users won't be sufficient, so this will need to support multiple files, at least. In addition, such flexible support will need a way to reload htpasswd file on the fly. And for many real-life use cases outside of the current "turn the basic auth on for dev", it will need the support of other stores as a plain file(s) is not really something that useful.

So, I don't see much value of per-route basic auth implemented in the core. I think this is an excellent case for a plugin and such a plugin can be as sophisticated as we need.

**Comment by umputun** [comment]
however, if anyone has a clever idea how to make it more flexible without adding much code and many new configuration parameters - we can discuss it. And we need to see a clear use case for proposed functionality

**Comment by p0123n** [comment]
Hey @umputun!

I wanted to mention that your middleware is excellent for testing purposes. However, there are instances where it becomes necessary to enable basic authentication only for specific services in the docker-compose setup.

Let's say we have a scenario where one service is "landing, under development, leave your email..." and another service needs to be protected.

Is there a convenient method to disable authentication for one or more services quickly? Thanks in advance for your help, and I appreciate any guidance you can provide!

**Comment by umputun** [comment]
> Is there a convenient method to disable authentication for one or more services quickly? Thanks in advance for your help, and I appreciate any guidance you can provide!

Not without a change. Adding a new parameter to `URLMapper` like "disable_basic_auth" or smth like this, parsing it for providers, and checking it in `basicAuthHandler` (URLMapper is a part of `ctxMatch` context value) will do the trick

**Pull request merged**
