### PR TITLE
Create cool site for Reproxy

### PR DESCRIPTION
**Pull request by akellbl4**
A lot of npm packages and beautiful configs :D
Also, amazing design and docs!

Preview is here: https://reproxy-git-site-akellbl4.vercel.app

### CODE REVIEW

**Comment by umputun** [comment]
is this thing need a build of some kind? If so, this should be added to actions I guess. Also not sure what the deployment directory

Any chance to see the demo of generated/built site somewhere?

**Comment by umputun** [comment]
ok, figured (hopefully) hot to try it. I did `npm run-script dev` to run it locally. One observation - navigation seems to be a little off in safari (works fine in chrome)

**Comment by umputun** [comment]
another question (suggestion) - it seems to have a copy of readme.md locally with one addition of the first "intro chapter". Can we just use the main README.md to generate the site? I mean, we can add the same intro, this is not a problem. I just afraid we will always forget to update the second location

**Comment by akellbl4** [comment]
I'll add docs about how to develop the site.
I use `yarn` as package manager.

`yarn` for install dependencies
`yarn dev` for local development
`yarn build` for production build

> navigation seems to be a little off in safari (works fine in chrome)
I'll check it.

> another question (suggestion) - it seems to have a copy of readme.md locally with one addition of the first "intro chapter". Can we just use the main README.md to generate the site? I mean, we can add the same intro, this is not a problem. I just afraid we will always forget to update the second location

Yes, it was my idea to use the same file.

What's about Dockerfile or smth like that for CD? I can prepare it.

**Comment by umputun** [comment]
> What's about Dockerfile or smth like that for CD? I can prepare it.

Well, we likely can avoid all of this and just add it to Makefile and run it manually? I mean to add site/pub to git (or whatever the build destination) and generate it manually after readme change.

**Comment by akellbl4** [comment]
@umputun got it. I've added everything. You can find the build in `site/public`. Now it's only one file ;)

**Comment by akellbl4** [comment]
@umputun okay, I managed using Readme as the content base of the site. Also, added favicons, logos, and sharing images.

**Comment by umputun** [comment]
looking cool indeed, thx. A couple of suggestions:

- can we add some juice to it? I mean all 3 sections here on white and kind of hard to distinguish. Maybe some different background for the header section?
- can we make the build procedure non-frontend-guru friendly? I.e. add a dockerfile to `site` installing all dependencies, run the build sequence, and copy results. Kind of similar to what we do for goreleaser (Dockerfile.artifacts)

**Comment by akellbl4** [comment]
- Yep, could be cool. I'll think about that. Could we do it in the next update?
- Sure, no problem.

**Comment by akellbl4** [comment]
@umputun what's about merge and deploy the site? :)

**Pull request merged**
